# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Captainhook < Formula
  desc "CaptainHook is a flexible git hooks manager that makes sharing git hooks a breeze"
  homepage "http://captainhook.info/"
  version "1.3.0"
  license "MIT"

  depends_on "git"
  depends_on "zsh" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/captainhook-go/captainhook/releases/download/1.3.0/captainhook_Darwin_x86_64.tar.gz"
      sha256 "8251849f33040cc205c457fba88d90d752bdcc0ffd0a4b58f2f4b3b40fe10fdb"

      def install
        bin.install "captainhook"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/captainhook-go/captainhook/releases/download/1.3.0/captainhook_Darwin_arm64.tar.gz"
      sha256 "bcd161490b8c352c1355e7263f65367c41555c1bc108d3842d596b6937a027ec"

      def install
        bin.install "captainhook"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/captainhook-go/captainhook/releases/download/1.3.0/captainhook_Linux_x86_64.tar.gz"
        sha256 "c9e300fc51a264ffb2246073586c8b7d15148a21bcaf8130c2a2ee83597271c0"

        def install
          bin.install "captainhook"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/captainhook-go/captainhook/releases/download/1.3.0/captainhook_Linux_arm64.tar.gz"
        sha256 "d3fe9dc38d20a12176a7641eb57324b871367c3c547ae878c9c0d74e1da5273a"

        def install
          bin.install "captainhook"
        end
      end
    end
  end
end
