# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Captainhook < Formula
  desc "CaptainHook is a flexible git hooks manager that makes sharing git hooks a breeze"
  homepage "http://captainhook.info/"
  version "1.0.0"
  license "MIT"

  depends_on "git"
  depends_on "zsh" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/captainhook-go/captainhook/releases/download/1.0.0/captainhook_Darwin_arm64.tar.gz"
      sha256 "4fa0ee554140c0e9d32170c7d258e4d618d1d55b44287b4e31ef8143a39cb563"

      def install
        bin.install "captainhook"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/captainhook-go/captainhook/releases/download/1.0.0/captainhook_Darwin_x86_64.tar.gz"
      sha256 "7045d435441f52aece5d8531ad82c305d9a330314ee7d6b92fae62b5fb18fa45"

      def install
        bin.install "captainhook"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/captainhook-go/captainhook/releases/download/1.0.0/captainhook_Linux_arm64.tar.gz"
      sha256 "7ccd5ead2d885ab03688f352526989dabd96e228eb6aa57d87c8f24175252943"

      def install
        bin.install "captainhook"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/captainhook-go/captainhook/releases/download/1.0.0/captainhook_Linux_x86_64.tar.gz"
      sha256 "30294009121396bde2530c1279580f78bc94b917ee1ad92d13951dd0bf835634"

      def install
        bin.install "captainhook"
      end
    end
  end
end
